version: "3"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend_container
        command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
        restart: always
        volumes:
            - ./backend:/app
        ports:
            - "8000:8000"
        depends_on:
            - postgres
    postgres:
        image: postgres:latest
        container_name: postgres_container
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:
